# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Laba9tests' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @wait = Selenium::WebDriver::Wait.new(timeout: 10)
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'check3' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('3')
    @driver.find_element(:id, 'submit').click
    @wait.until{@driver.find_element(:id, 'result').displayed?}
    expect(@driver.find_element(:xpath, "//p[@id='result']").text).to eq("153: 1^3 + 5^3 + 3^3\n370: 3^3 + 7^3 + 0^3\n371: 3^3 + 7^3 + 1^3\n407: 4^3 + 0^3 + 7^3")
  end
  it 'check5' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('5')
    @driver.find_element(:id, 'submit').click
    @wait.until{@driver.find_element(:id, 'result').displayed?}
    expect(@driver.find_element(:xpath, "//p[@id='result']").text).to eq("54748: 5^5 + 4^5 + 7^5 + 4^5 + 8^5\n92727: 9^5 + 2^5 + 7^5 + 2^5 + 7^5\n93084: 9^5 + 3^5 + 0^5 + 8^5 + 4^5")
  end
  it 'checkempty' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:id, 'submit').click
    @wait.until{@driver.find_element(:id, 'result').displayed?}
    expect(@driver.find_element(:xpath, "//p[@id='result']").text).to eq('Incorrect!')
  end
  it 'checkincorrect' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:id, 'arm_form').click
    @driver.find_element(:id, 'v1').send_keys('123')
    @driver.find_element(:id, 'submit').click
    @wait.until{@driver.find_element(:id, 'result').displayed?}
    expect(@driver.find_element(:xpath, "//p[@id='result']").text).to eq('Incorrect!')
  end
end
