# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Laba10' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'servercorrect' do
    @driver.get('http://localhost:3001/')
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('3')
    @driver.find_element(:id, 'server-side').click
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:id, 'res').text).to eq('Генерация на стороне сервера')
    expect(@driver.find_element(:xpath, '//p').text).to eq('Числа Армстронга длиной 3')
  end
  it 'browsercorrect' do
    @driver.get('http://localhost:3001/')
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('3')
    @driver.find_element(:id, 'client-side-xslt').click
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:id, 'res').text).to eq('Генерация на стороне браузера')
    expect(@driver.find_element(:xpath, '//p').text).to eq('Числа Армстронга длиной 3')
  end
  it 'browserincorrect' do
    @driver.get('http://localhost:3001/')
    @driver.manage.resize_to(794, 664)
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('hello')
    @driver.find_element(:css, 'label:nth-child(9)').click
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:id, 'res').text).to eq('Генерация на стороне браузера')
    expect(@driver.find_element(:xpath, '//p').text).to eq('Некорректный ввод!')
  end
  it 'serverincorrect' do
    @driver.get('http://localhost:3001/')
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('123')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:id, 'res').text).to eq('Генерация на стороне сервера')
    expect(@driver.find_element(:xpath, '//p').text).to eq('Некорректный ввод!')
  end
end
